### ISSUE TITLE
Adding callback on response (then)

### ISSUE THREAD

**Issue by ahoarau** [rpclib/rpclib#162] opened 2017-11-06 13:29 UTC
For GUIs, it would be very useful if we could bind a callback for the response. Something like : 
```c++
#include "rpc/client.h"

int main() {
    rpc::client c("127.0.0.1", 8080);
   // aync_call or call 
    auto a_future = c.async_call("add", 2, 3).then( [](int result) {
                                          std::cout << "Update GUI" << std::endl;
                                          } );

    return 0;
}
```

related to #45

**Comment by sztomi** [comment] 2017-11-06 14:07
I'd say it's a straight duplicate of #45, isn't it?

**Comment by sztomi** [comment] 2017-11-06 14:38
Let's close this one and let's explore some options under #45. `.then` is not the only option for a callback.

**Closed by sztomi** 2017-11-06 14:38 UTC
