### ISSUE TITLE
Compile error on OSX

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#154] opened 2017-09-19 08:16 UTC
We are getting below error when compiling our library on OSX that uses rpclib. I'm wondering if anyone has insight. BTW, we are using version from from Apr 29, (commit 3c0a23da7356bd31ed8a81a76771dade0f8a7b72).

```
/deps/rpclib/include/rpc/msgpack/adaptor/nil.hpp:32:1: error: declaration of anonymous struct must be a definition
struct nil { };
^
/deps/rpclib/include/rpc/msgpack/adaptor/nil.hpp:34:23: error: expected parameter declarator
inline bool operator<(nil const& lhs, nil const& rhs) {
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
      #define nil nullptr
                  ^

```

**Comment by sztomi** [comment] 2017-09-19 08:37
Could you try out 6f416f0 ? This is not a released state (currently the tip of the dev branch), but I'll soon make a release. I'm compiling this version along with the unit tests on OSX without problems.

**Comment by sztomi** [comment] 2017-09-27 22:20
Based on the comment [here](https://github.com/Microsoft/AirSim/issues/469#issuecomment-332437501) it seems to me that the mentioned commit did solve the issue with rpclib and the remaining problems are outside it. Closing the issue (feel free to reopen if misjudged the situation).

**Closed by sztomi** 2017-09-27 22:20 UTC

**Comment by ProfFan** [comment] 2017-10-18 05:47
@sztomi Confirmed that the error is caused by `nil` conflicting with some reserved word in the compiler. Changed all `nil` to `nil_t` solved this issue.

**Comment by sytelus** [comment] 2017-11-13 23:16
Just wondering how https://github.com/rpclib/rpclib/commit/6f416f0ae588b3c2d69509446d1826a9d5d416d9 fixed this issue? It just looks like change in travis yml. Don't we have to change nil to nil_t as above comment https://github.com/rpclib/rpclib/issues/154#issuecomment-337466725 said?

**Comment by sztomi** [comment] 2017-11-14 10:24
@sytelus that is not the exact commit that fixed the build just whatever the latest was when I posted it.

If your code has problems with nil in C++ then you are compiling it as Objective-C++ which rpclib has no explicit support for. That being said, #152 changed nil to nil_t anyway. 

Are you aware that there is a new release out now (technically, two, with one being a hotfix)?
