### ISSUE TITLE
rpclib leaks and crashes after ~1000 consecutive connections to an rpclib server

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#125] opened 2017-05-24 22:09 UTC
@sztomi 

a simple rpclib server will eventially crash after ~1000 consecutive connections.
Looks like the server doesn't properly release the connection to a client after client goes out of scope. How would I properly close the client?

test_leak crashes, test_no_leak doesn't crash.

```
void test_leak(){
  for(int counter=0; ; counter++){
    rpc::client client(host, port);
    auto response = client.call("fun", "arg").as<string>();
  }
}

void test_no_leak(){
   rpc::client client(host, port);
   for(int counter=0; ; counter++){
     auto response = client.call("fun", "arg").as<string>();
  }
}
```

* `ls -l /proc/$pid/fd  | wc -l` keeps increasing
* htop shows memory keeps increasing
* `lsof -p $pid` keeps increasing, showing entries such as:
```
binary $pid user  ...     IPv4 ...      0t0      TCP localhost:18700->localhost:39692 (ESTABLISHED)
```

EDIT:
for the server, use this for eg:`bind("fun", []() { return ""; });`

**Comment by sztomi** [comment] 2017-05-25 10:20
Thank you for reporting this, it looks like a bug. 

> Looks like the server doesn't properly release the connection to a client after client goes out of scope.

Was your server in a different process or is this just an assumption?

**Comment by timotheecour** [comment] 2017-05-25 13:25
Different process

**Comment by sztomi** [comment] 2017-05-28 12:42
I was able to reproduce this, fix is on the way.

**Comment by sztomi** [comment] 2017-05-28 13:34
Fixed, on `dev` branch. Will be part of the next release.

**Comment by timotheecour** [comment] 2017-07-07 16:29
Hi @zstomi any ETA on this? thanks!

**Comment by sztomi** [comment] 2017-07-09 12:07
@timotheecour I want to release it in a week or so.

**Comment by sztomi** [comment] 2017-07-15 10:20
This was released: https://github.com/rpclib/rpclib/releases/tag/v2.1.0

**Closed by sztomi** 2017-07-15 10:20 UTC
Labels: bug, Waiting for Release
