### ISSUE TITLE
RPC Call Fails on large input calls

### ISSUE THREAD

**Issue by drdesai** [rpclib/rpclib#90] opened 2017-01-13 00:53 UTC
When a very large string (80k bytes) to the echo example, the client only displays the first 4102.

To reproduce:

compile the echo_client and echo_server example and input a ridiculously large string. Only a subset of the string will be output.

**Comment by sztomi** [comment] 2017-01-14 13:24
Interesting, are you using the 1.0.0 tag or the 1.0.0 pre-release? Before 1.0.0, the server could not handle large inputs (although it should have crashed). The mandelbrot example was designed to check that large data can be transmitted, could you try that out with your setup?

**Comment by drdesai** [comment] 2017-01-15 01:06
I'm using the 1.0.0 tag, specifically [this release](https://github.com/rpclib/rpclib/archive/1.0.0.zip). With a clean clone and generation, this behavior still happens.

Logs:
[client.txt](https://github.com/rpclib/rpclib/files/706334/client.txt)
[server.txt](https://github.com/rpclib/rpclib/files/706333/server.txt)

System Info:
uname -a: Linux archlinux.vagrant.vm 4.8.13-1-ARCH x86_64 GNU/Linux
Compiler: gcc 6.3.1
CMAKE: cmake 3.7.1

**Comment by sztomi** [comment] 2017-01-15 09:40
Thanks, very much appreciated. BTW, I have not yet formally released 1.0.0, but github treats all tags as releases, unfortunately. It's great that someone is actively taking a look.

**Comment by sztomi** [comment] 2017-01-15 22:34
I was able to reproduce this bug. It seems that on the client side, `text` is sized exactly 4095 right after reading from `cin`, which is the size the client reads back from the server (note that the whole buffer is bigger than the string itself, that's why the log says 4102). So I'm thinking that `std::getline` is the culprit here somehow. I'll try to either make it work or replace it with something else. In the meantime, if you want to test large inputs/outputs in RPC calls, I suggest the mandelbrot examples.

**Comment by sztomi** [comment] 2017-01-15 22:36
It is also possible that the terminal itself cuts the input.

**Comment by sztomi** [comment] 2017-01-15 23:45
@drdesai So that was a pretty good guess, but it's not even the terminal, it's the kernel. The kernel has a constant called [N_TTY_BUF_SIZE](http://lxr.free-electrons.com/source/include/linux/tty.h#L321) which has been 4096 since ancient times - and still is! It looks like your test runs into this exact limitation. Consider the following client:

```cpp
#include "rpc/client.h"

#include <iostream>

int main() {
    rpc::client c("localhost", 8080);

    std::string text;
    while (std::getline(std::cin, text)) {
        if (!text.empty()) {
            std::cout << "TEXT SIZE = " << text.size() << std::endl;
            std::string result(c.call("echo", text).as<std::string>());
            std::cout << "RESULT SIZE = " << result.size() << std::endl;
        }
    }
}
```

When using the terminal to input the long string, the output is the following:

```
2017-01-16 00:33:07.324  INFO    client          Initiating connection.                  
2017-01-16 00:33:07.325  INFO    client          Client connected to localhost:8080      
2017-01-16 00:33:07.326  TRACE   client          do_read (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:59)
<< input long lorem ipsum here >>
TEXT SIZE = 4095
2017-01-16 00:33:09.741  TRACE   client          Read chunk of size 4102 (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:72)
RESULT SIZE = 4095
2017-01-16 00:33:09.742  TRACE   client          do_read (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:59)
```

However, if the long lorem ipsum is stored in a file and piped to the client, the correct size is read is sent and read back:

```
$ ls -al inputfile 
-rw-r--r-- 1 sztomi users 71681 Jan 16 00:21 inputfile

$ cat inputfile | ./output/bin/echo_client
2017-01-16 00:37:44.567  INFO    client          Initiating connection.                  
2017-01-16 00:37:44.569  INFO    client          Client connected to localhost:8080      
2017-01-16 00:37:44.569  TRACE   client          do_read (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:59)
TEXT SIZE = 71680
2017-01-16 00:37:44.594  TRACE   client          Read chunk of size 65535 (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:72)
2017-01-16 00:37:44.594  TRACE   client          do_read (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:59)
2017-01-16 00:37:44.594  TRACE   client          Read chunk of size 6154 (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:72)
RESULT SIZE = 71680
2017-01-16 00:37:44.594  TRACE   client          do_read (/home/sztomi/Projects/rpclib/rpclib/lib/rpc/client.cc:59)
```

This is the expected output. Note that the one byte difference is the line feed which `std::getline` strips.
 If I had to guess, the kernel is not changing this size because it's a good enough size for human input - if you want more, you would probably be piping it anyway in real-world scenarios. I'm closing this issue now, but please let me know if the above piping doesn't work for you.

**Closed by sztomi** 2017-01-15 23:45 UTC
Labels: bug, in progress
